{
 "title": "MiCADO Grafana Dashboard - jQueuer",
 "description": "MiCADO Grafana Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node ID", "query": "label_values(node)" },
   { "name": "expid", "label": "Experiment ID", "query": "label_values(experiment_id)" },
   {
    "name": "service_name",
    "label": "Service",
    "query": "query_result(count(container_last_seen{container_label_io_kubernetes_container_name=~\".+\"}) by (container_label_io_kubernetes_container_name))"
   },
   {
    "name": "instance",
    "label": "Hostnames",
    "query": "query_result(count(up{instance=~\".+\"}) by (instance))"
   },
   { "name": "topk", "label": "Top Cont.", "query": "5,10,20,50,100,1000" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "worker",
    "label": "MasterNode",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General Info & Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_load1{node=~\"$node\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_io_kubernetes_docker_type!=\"podsandbox\", container_label_io_kubernetes_pod_name=~\"$service_name-.*\"}[$interval]))"
    }
   ]
  },
  { "title": "jQueuer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Jobs Completed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(jqueuer_job_accomplished{experiment_id=~\"$expid\"} == 1)"
    }
   ]
  },
  {
   "title": "Jobs Completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 2, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(jqueuer_job_accomplished{experiment_id=~\"$expid\"} == 1)",
     "legendFormat": "{{host}}"
    },
    { "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Jobs Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(jqueuer_job_running{experiment_id=~\"$expid\"} == 1)"
    }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "jqueuer_experiment_deadline{experiment_id=~\"$expid\"}-time()"
    }
   ]
  },
  {
   "title": "Jobs Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(jqueuer_job_added{experiment_id=~\"$expid\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(jqueuer_job_failed)" }
   ]
  },
  {
   "title": "Resource Usage (per Node/Container)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage per node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",node=~\"$node\"}[$interval])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage per Container (Stacked)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": " label_replace(topk($topk, sum without (cpu) (irate(container_cpu_usage_seconds_total{container_label_io_kubernetes_docker_type!=\"podsandbox\", container_label_io_kubernetes_pod_name=~\"$service_name-.*\"}[1m])) * 100), \"task_name\", \"$1\", \"container_label_io_kubernetes_pod_name\", \"(.*)\")",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Memory usage per node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemAvailable_bytes{node=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage per Container (Stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(topk($topk, sum(container_memory_usage_bytes{container_label_io_kubernetes_docker_type!=\"podsandbox\", container_label_io_kubernetes_pod_name=~\"$service_name-.*\"}) by (name, container_label_io_kubernetes_pod_name)), \"task_name\", \"$1\", \"container_label_io_kubernetes_pod_name\", \"(.*)\")",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Alerts Fired In Prometheus",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 4, "y": 28 },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic on Cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total[$interval]))",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total[$interval]))",
       "legendFormat": "SENT"
      }
     ]
    },
    {
     "title": "Received Network Traffic per Container (Stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "label_replace(topk($topk, rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_name=~\"$service_name-.*\"}[2m])*100), \"task_name\", \"$1\", \"container_label_io_kubernetes_pod_name\", \"(.*)\")",
       "legendFormat": "{{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Versions",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "{{instance}} cAdvisor Version: {{cadvisorVersion}}"
      },
      {
       "expr": "prometheus_build_info",
       "legendFormat": "{{instance}} Prometheus Version: {{version}}"
      },
      {
       "expr": "node_exporter_build_info",
       "legendFormat": "{{instance}} Node-Exporter Version: {{version}}"
      },
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "{{instance}} Docker Version: {{dockerVersion}}"
      },
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "{{instance}} Host OS Version: {{osVersion}}"
      },
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "{{instance}} Host Kernel Version: {{kernelVersion}}"
      }
     ]
    }
   ]
  }
 ]
}